let cipher = require('./vigenere-cipher.js')
console.log(String.fromCharCode(78))
let encrypt =cipher.prototype.encrypt('attack at dawn!', 'alphonse')
console.log(encrypt)
console.log(cipher.prototype.decrypt(encrypt, 'alphonse'))
